export const styles = {
  container: {
    fontFamily: 'Arial, sans-serif',
    textAlign: 'center' as const,
    padding: '40px',
    backgroundColor: 'var(--background)',
    minHeight: '100vh',
    position: 'relative' as const,
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 20px',
    backgroundColor: '#388e3c',
  },
  iconButton: {
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '24px',
    color: 'white',
  },
  hamburgerIcon: {
    fontSize: '24px',
  },
  settingsIcon: {
    fontSize: '24px',
  },
  menu: {
    position: 'fixed' as const,
    top: '0',
    left: '0',
    width: '250px',
    height: '100%',
    backgroundColor: '#ffffff',
    boxShadow: '2px 0 5px rgba(0, 0, 0, 0.2)',
    zIndex: 1000,
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  closeButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#4caf50',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '16px',
    marginBottom: '20px',
  },
  settingsMenu: {
    position: 'fixed' as const,
    top: '0',
    right: '0',
    width: '300px',
    height: '100%',
    backgroundColor: '#ffffff',
    boxShadow: '-2px 0 5px rgba(0, 0, 0, 0.2)',
    zIndex: 1000,
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  settingsCloseButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#4caf50',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '16px',
    marginBottom: '20px',
  },
  menuList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  menuItem: {
    padding: '10px 0',
    fontSize: '18px',
    color: '#388e3c',
    cursor: 'pointer',
    borderBottom: '1px solid #e0e0e0',
  },
  header: {
    backgroundColor: 'var(--secondary-color)',
    color: 'var(--foreground)',
    padding: '30px 0',
    borderBottom: '6px solid var(--accent-color)',
  },
  title: {
    margin: 0,
    fontSize: '72px',
    fontWeight: 'bold',
    color: 'var(--accent-color)',
  },
  introSection: {
    marginTop: '40px',
    marginBottom: '40px',
  },
  introTitle: {
    fontSize: '48px',
    color: '#2e7d32',
    margin: '20px 0',
    fontWeight: 'bold',
  },
  introDescription: {
    fontSize: '24px',
    color: '#388e3c',
  },
  main: {
    marginTop: '40px',
  },
  description: {
    fontSize: '24px',
    marginBottom: '30px',
    color: '#2e7d32',
    fontWeight: 'bold',
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '30px',
  },
  buttonWrapper: {
    textAlign: 'center' as const,
  },
  button: {
    padding: '20px 40px',
    fontSize: '20px',
    backgroundColor: 'var(--primary-color)',
    color: 'var(--foreground)',
    border: '3px solid var(--secondary-color)',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'background-color 0.3s, transform 0.2s',
    fontWeight: 'bold',
  },
  languageDescription: {
    marginTop: '15px',
    fontSize: '18px',
    color: '#2e7d32',
  },
  footer: {
    marginTop: '50px',
    fontSize: '18px',
    color: '#388e3c',
    fontWeight: 'bold',
  },
};